esphome:
  name: esphome-base-image
  friendly_name: esphome-base-image

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "KtD5wf3uPqImNs84Gd3F1AWj9RQWWoVYa1YuVpFHSQM="

ota:
  - platform: esphome
    password: "b041b590219dbc0c3d7076a7b558d35e"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Base-Image"
    password: "NMlWBGxPRYfx"

captive_portal:
    