esphome:
  name: pantry_esp32
  friendly_name: Pantry ESP32

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:

captive_portal:

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms  # Adjust as needed
    window: 1100ms

bluetooth_proxy:

sensor:
  - platform: wifi_signal
    name: "WiFi Signal Strength"
    update_interval: 300s
    disabled_by_default: true

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "WiFi IP Address"
      disabled_by_default: true
    ssid:
      name: "WiFi SSID"
      disabled_by_default: true

output:
  - platform: ledc
    pin: GPIO2  # Change to your chosen GPIO
    id: blue_led

switch:
  - platform: output
    name: "blue_led"
    output: blue_led
    internal: false  # Allows it to be visible in Home Assistant
    entity_category: diagnostic  # Categorizes it as a diagnostic entity
    disabled_by_default: true

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO12
      mode: INPUT_PULLUP
      inverted: true
    name: "Input 1"
    
  - platform: gpio
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
      inverted: true
    name: "Input 2"

  - platform: gpio
    pin:
      number: GPIO14
      mode: INPUT_PULLUP
      inverted: true
    name: "Input 3"

  - platform: gpio
    pin:
      number: GPIO15
      mode: INPUT_PULLUP
      inverted: true
    name: "Input 4"

  - platform: gpio
    pin:
      number: GPIO16
      mode: INPUT_PULLUP
      inverted: true
    name: "Input 5"
